### ISSUE TITLE
what is wrong?

### ISSUE THREAD

**Issue by tirelibirefe** [imajeetyadav/rsync-deployer#1]
Hello,
My config is  :

```
        HOST: "5.45.231.203"
        USERNAME: spiderman
        KEY: "b3BlbnNzaC1rZXktdXXXXXX"
        SOURCE_PATH: "./e-mahallende/bin/Release/net7.0/publish/"
        TARGET_PATH: "/var/www/html/"
        # BACKUP_PATH: "/home/ubuntu/test-backup/"
        PORT: 22
        RSYNC_PARAMETERS: "" 
        ...
```
but I get following error. The KEY is the "private" part of the key which is the content of id_ed25519.

`Error loading key "/dev/fd/64": error in libcrypto`

What am I missing?

Thanks

**Comment by imajeetyadav** [comment]
Please check your private.

You can use this command to generate new `ssh-keygen -m PEM -t rsa -b 4096`
